version: '3'
services:
  web:
    build: 
        context: ./socket
    ports:
     - "8080:3000"
    volumes:
     - "./socket:/code"
  db:
    image: postgres:latest
    ports:
      - "5454:5454"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
