version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  api:
    build: 
        context: ./socket
    ports:
     - "8080"
    volumes:
     - "./socket:/code"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formulaDB
  grafana:
    image: grafana/grafana
    ports:
      - "3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,yesoreyeram-boomtable-panel,briangann-gauge-panel,bessler-pictureit-panel,natel-plotly-panel,jdbranham-diagram-panel,vonage-status-panel"
