version: '3'
services:
  web:
    build: 
        context: ./tornado
    ports:
     - "8888:8888"
    volumes:
     - "./tornado:/code"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"