version: '3'
services:
  ngnix:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - grafana
  api:
    build: 
        context: ./socket
    ports:
     - "8080"
    volumes:
     - "./socket:/code"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formulaDB
  grafana:
    image: grafana/grafana
    ports:
      - "3000"
