version: '3'
services:
  db:
    image: timescale/timescaledb:latest-pg10
    ports:
     - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formulaDB
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DATA_ENGINE: tsm1
      INFLUXDB_REPORTING_DISABLED: false
    volumes:
      - /srv/docker/influxdb/data:/var/lib/influxdb
  api:
    restart: always
    build:
        context: ./socket
    ports:
     - "8080"
    volumes:
     - "./socket:/code"
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: api.matadormotorsports.racing
      LETSENCRYPT_HOST: api.matadormotorsports.racing
      LETSENCRYPT_EMAIL: csun.fsae.2018@gmail.com
  grafana:
    user: root
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - certs:/etc/letsencrypt/certs:ro
    image: grafana/grafana:master
    ports:
      - "3000"
    environment:
      VIRTUAL_HOST: matadormotorsports.racing
      LETSENCRYPT_HOST: matadormotorsports.racing
      LETSENCRYPT_EMAIL: csun.fsae.2018@gmail.com
      GF_METRICS_ENABLED: "true"
      GF_SECURITY_DISABLE_GRAVATAR: "true"
      GF_SERVER_ROOT_URL: "https://matadormotorsports.racing"
      GF_INSTALL_PLUGINS: "grafana-clock-panel,yesoreyeram-boomtable-panel,briangann-gauge-panel,bessler-pictureit-panel,natel-plotly-panel,jdbranham-diagram-panel,vonage-status-panel,grafana-worldmap-panel,snuids-radar-panel,marcuscalidus-svg-panel"
      # GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_GOOGLE_ENABLED: "true"
      GF_AUTH_GOOGLE_CLIENT_ID: "${CLIENT_ID}"
      GF_AUTH_GOOGLE_CLIENT_SECRET: "${CLIENT_SECRET}"
      GF_AUTH_GOOGLE_SCOPES: "https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email"
      GF_AUTH_GOOGLE_AUTH_URL: "https://accounts.google.com/o/oauth2/auth"
      GF_AUTH_GOOGLE_TOKEN_URL: "https://accounts.google.com/o/oauth2/token"
      GF_AUTH_GOOGLE_ALLOWED_DOMAINS: "my.csun.edu csun.edu matadormotorsports.racing"
      GF_AUTH_GOOGLE_ALLOW_SIGN_UP: "true"
      GF_SESSION_PROVIDER: "memory"
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam:ro
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    restart: always
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

networks:
  default:
    external:
      name: nginx-proxy
