version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: formulaDB
  api:
    build: 
        context: ./socket
    ports:
     - "8080"
    volumes:
     - "./socket:/code"
    depends_on:
      - db
  grafana:
    image: grafana/grafana
    ports:
      - "3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,yesoreyeram-boomtable-panel,briangann-gauge-panel,bessler-pictureit-panel,natel-plotly-panel,jdbranham-diagram-panel,vonage-status-panel"
  nginx:
    image: nginx:latest
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - api
      - db
      - grafana